version: '3.8'
services:
  db:
    container_name: demo_testing_for_fpb_functionality
    image: postgres:alpine
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
volumes:
  data:
